server:
  port: 8888

spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix:
      classpath: /templates/

logging:
  config:
    classpath: logback.xml

chudichen:
  elasticsearch:
    ip: 127.0.0.1:5601